// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WindowsFormsApp1;

namespace WindowsFormsApp1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("WindowsFormsApp1.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContractTime");

                    b.Property<string>("Customer");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("OrderId");

                    b.Property<string>("Performer");

                    b.Property<string>("Subject");

                    b.Property<int>("TotalCost");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("WindowsFormsApp1.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientBankInfo");

                    b.Property<int?>("ClientId");

                    b.Property<string>("Comment");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OrderStatusId");

                    b.Property<string>("Organization");

                    b.Property<int?>("PerformerId");

                    b.Property<string>("SoftwareName");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PerformerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WindowsFormsApp1.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("NameRole");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WindowsFormsApp1.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Duration");

                    b.Property<string>("Name");

                    b.Property<int?>("OrderIdId");

                    b.Property<int?>("PerformerId");

                    b.Property<int>("Priсe");

                    b.HasKey("Id");

                    b.HasIndex("OrderIdId");

                    b.HasIndex("PerformerId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("WindowsFormsApp1.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("WindowsFormsApp1.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<int?>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WindowsFormsApp1.Contract", b =>
                {
                    b.HasOne("WindowsFormsApp1.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("WindowsFormsApp1.Order", b =>
                {
                    b.HasOne("WindowsFormsApp1.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("WindowsFormsApp1.Status", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId");

                    b.HasOne("WindowsFormsApp1.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId");
                });

            modelBuilder.Entity("WindowsFormsApp1.Stage", b =>
                {
                    b.HasOne("WindowsFormsApp1.Order", "OrderId")
                        .WithMany()
                        .HasForeignKey("OrderIdId");

                    b.HasOne("WindowsFormsApp1.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId");
                });

            modelBuilder.Entity("WindowsFormsApp1.User", b =>
                {
                    b.HasOne("WindowsFormsApp1.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
